name: iclick_books_manager
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Flutter Bloc
  flutter_bloc: ^7.2.0

  #Http Client
  http: ^0.13.4

  #Cached Network Image
  cached_network_image: ^3.1.0

  #Equatable
  equatable: ^2.0.3

  #Json Annotation
  json_annotation: ^4.4.0

  #Cupertino Icons
  cupertino_icons: ^1.0.6

  #Auto Route Generator
  auto_route_generator: ^8.0.0

  # Connectivity
  connectivity_plus: ^6.0.3

  # responsive ui
  responsive_sizer: ^3.3.1

  provider: ^6.0.0
  json_serializable: ^6.8.0

  # Service locator
  get_it: ^7.1.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          anyMap: true
