import 'package:flutter/material.dart';

abstract class BaseComponentsThemeData {
  AppBarTheme? get appBarTheme;
  InputDecorationTheme? get inputDecorationTheme;
  IconThemeData? get iconThemeData;
  IconThemeData? get primaryIconTheme;
  IconThemeData? get accentIconTheme;
  SliderThemeData? get sliderTheme;
  TabBarTheme? get tabBarTheme;
  TooltipThemeData? get tooltipTheme;
  CardTheme? get cardTheme;
  ChipThemeData? get chipTheme;
  TargetPlatform? get platform;
  MaterialTapTargetSize? get materialTapTargetSize;
  PageTransitionsTheme? get pageTransitionsTheme;
  ScrollbarThemeData? get scrollbarTheme;
  BottomAppBarTheme? get bottomAppBarTheme;
  ColorScheme? get colorScheme;
  DialogTheme? get dialogTheme;
  FloatingActionButtonThemeData? get floatingActionButtonTheme;
  NavigationRailThemeData? get navigationRailTheme;
  Typography? get typography;
  SnackBarThemeData? get snackBarTheme;
  BottomSheetThemeData? get bottomSheetTheme;
  PopupMenuThemeData? get popupMenuTheme;
  MaterialBannerThemeData? get bannerTheme;
  DividerThemeData? get dividerTheme;
  ButtonBarThemeData? get buttonBarTheme;
  BottomNavigationBarThemeData? get bottomNavigationBarTheme;
  TimePickerThemeData? get timePickerTheme;
  TextButtonThemeData? get textButtonTheme;
  ElevatedButtonThemeData? get elevatedButtonTheme;
  OutlinedButtonThemeData? get outlinedButtonTheme;
  TextSelectionThemeData? get textSelectionTheme;
  DataTableThemeData? get dataTableTheme;
  CheckboxThemeData? get checkboxTheme;
  RadioThemeData? get radioTheme;
  SwitchThemeData? get switchTheme;
  ButtonThemeData? get getbuttonTheme;
  ToggleButtonsThemeData? get toggleButtonsTheme;
}
